CREATE TABLE IF NOT EXISTS customers(
    id SERIAL PRIMARY KEY,
    login VARCHAR(20) UNIQUE,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR,
    phone VARCHAR(13),
    type VARCHAR NOT NULL
);
